services:
  app:
    image: ghcr.io/an0sis/mlops-tp1:latest
    container_name: mlops-app
    restart: unless-stopped
    ports:
      - "8765:8765"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true

networks:
  default:
    name: app-network
